# Common settings
proj_name: multi_airfoil_enf
seed: 42
logging:
    log_dir: './experiments/training/'

dataset:
  name: 'multielement_airfoil'  # or 'rae_transonic'
  root_path: '/home/dmsm/gi.catalani/Projects/enf2enf/multi_airfoil'  # adjust path as needed
  task: null
  target_fields: null
  num_points: null  # optional subsampling

geometry_encoder:
  logging:
    checkpoint: true
    checkpoint_every_n_epochs: 5
    keep_n_checkpoints: 3
    log_dir: './experiments/training/'

  seed: 42
  experiment_dir: 'geometry_encoder'
  model:
    num_hidden: 128
    num_heads: 2
    num_layers: 0
    num_out: 1
    latent_dim: 8
    gaussian_window: 0.1
    num_latents: 4
    coord_dim: 2
    spatial_dim: 2
    embedding_type: 'rff'
    embedding_freq_multiplier: [1,1]
    condition_value_transform: true
    freeze_lat_pos: true
    latent_bbox: [[-0.5,0.25],[-0.25,0.25]]  # Set this to the bounding box of your dataset
    checkpoint_directory: null

  optimizer:
    learning_rate_enf: 0.0001
    learning_rate_codes: 0.0

  training:
    num_inner_steps: 3
    num_sampled_points: 5000
    learning_rate_enf: 0.0001
    learning_rate_meta_sgd: 1e-4
    learning_rate_codes: 0.0
    num_epochs: 1000
    batch_size: 1
    val_batch_size: 1

  meta:
    inner_learning_rate_p: 0.0
    inner_learning_rate_a: 1
    inner_learning_rate_window: 0.0
    learning_rate_meta_sgd: 1e-4


